### ISSUE TITLE
building for iOS device

### ISSUE THREAD

**Issue by johnhaitas** [instructure/CKRefreshControl#5]
CKRefreshControl is a dependency of a static library

error is as follows:

Undefined symbols for architecture armv7s:
  "_OBJC_CLASS_$_CKRefreshControl", referenced from:
      objc-class-ref in libTGOSDK.a(TGOViewController.o)
ld: symbol(s) not found for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

was previously working with changes i made on bad pull request earlier ...

can be fixed by  removing ONLY_ACTIVE_ARCH = YES; from Debug configuration
